version: '3.8'

services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: app

  test:
    build: .
    command: pytest
    volumes:
      - .:/usr/src/app
    environment:
      FLASK_ENV: testing
      FLASK_APP: app

  init-db:
    build: .
    command: python init_db.py
    volumes:
      - .:/usr/src/app
    environment:
      FLASK_ENV: development
      FLASK_APP: app